services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi/postgresql
    ports:
      - 8000:8000
    networks:
      - bookstore-network
    depends_on:
      - database
      - redis
      - jaeger

  redis:
    image: "redis:8.4.0-alpine"
    ports:
      - 6379:6379
    networks:
      - bookstore-network
  
  database:
    image: "postgres:18-alpine"
    restart: always
    shm_size: 512mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: fastapi
      POSTGRES_PASSWORD: s3cur3p4ssw0rd
      POSTGRES_DB: bookstore
    volumes:
      - db-data:/var/lib/postgresql
    networks:
      - bookstore-network

  jaeger:
    image: jaegertracing/all-in-one:1.76.0
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"  # Jaeger UI
      - "4318:4318"    # OTLP HTTP receiver
    networks:
      - bookstore-network

networks:
  bookstore-network:
    driver: bridge

volumes:
  db-data: